In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame({'x0' : [1,2,3,4,5],
                    'x1' : [0.01, -0.01, 0.25, -4.1, 0.],
                    'y' : [-1.5, 0., 3.6, 1.3, -2.]})
data

,x0,x1,y
0,1,0.01,-1.5
1,2,-0.01,0.0
2,3,0.25,3.6
3,4,-4.10,1.3
4,5,0.00,-2.0


In [3]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [4]:
data.values

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [5]:
df2 = pd.DataFrame(data.values, columns=['one', 'two', 'three'])
df2

,one,two,three
0,1.0,0.01,-1.5
1,2.0,-0.01,0.0
2,3.0,0.25,3.6
3,4.0,-4.10,1.3
4,5.0,0.00,-2.0


In [6]:
df3 = data.copy()

In [7]:
df3['strings'] = ['a', 'b', 'c', 'd', 'e']
df3

,x0,x1,y,strings
0,1,0.01,-1.5,a
1,2,-0.01,0.0,b
2,3,0.25,3.6,c
3,4,-4.10,1.3,d
4,5,0.00,-2.0,e


In [8]:
df3.values #.values 속성은 데이터가 한가지 타입일때만, 만약 속성이 한가지가 아니라면 ndarray가 반환

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

In [10]:
model_cols = ['x0', 'x1']
data.loc[:, model_cols].values

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [11]:
data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'], categories= ['a', 'b'])
data

,x0,x1,y,category
0,1,0.01,-1.5,a
1,2,-0.01,0.0,b
2,3,0.25,3.6,a
3,4,-4.10,1.3,a
4,5,0.00,-2.0,b


In [12]:
dummies = pd.get_dummies(data.category, prefix= 'category')
data_with_dummies = data.drop('category', axis= 1).join(dummies)
data_with_dummies

,x0,x1,y,category_a,category_b
0,1,0.01,-1.5,1,0
1,2,-0.01,0.0,0,1
2,3,0.25,3.6,1,0
3,4,-4.10,1.3,1,0
4,5,0.00,-2.0,0,1


In [13]:
#Patsy를 이용해서 모델 생성
#Patsy : 통계모델(특히 선형모델)을 위한 파이썬 라이브러리
#Patsy의 수식 문법 : y ~ x0 + x
data = pd.DataFrame({'x0' : [1, 2, 3, 4, 5], 'x1' : [0.01, -0.01, 0.25, -4.1, 0.], 'y' : [-1.5, 0., 3.6, 1.3, -2.]})
data


,x0,x1,y
0,1,0.01,-1.5
1,2,-0.01,0.0
2,3,0.25,3.6
3,4,-4.10,1.3
4,5,0.00,-2.0


In [18]:
pip install patsy

Note: you may need to restart the kernel to use updated packages.
You should consider upgrading via the 'C:\Users\seven\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [19]:
import patsy

In [20]:
y, X = patsy.dmatrices('y ~ x0 + x1', data)

In [21]:
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [22]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [23]:
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [24]:
np.asarray(X)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

In [25]:
#모델에 0을 더해서 intercept 제거
patsy.dmatrices('y ~ x0 + x1 + 0', data)[1]

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

In [26]:
coef, resid, _, _ = np.linalg.lstsq(X, y) #Pasty객체를 최소제곱회귀분석을 위해 알고리즘에 넘기기

<ipython-input-26-ef4372856a50>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  coef, resid, _, _ = np.linalg.lstsq(X, y)


In [27]:
#모델 메타데이터 => design_info속성을 통해 얻음
coef

array([[ 0.31290976],
       [-0.07910564],
       [-0.26546384]])

In [29]:
coef = pd.Series(coef.squeeze(), index = X.design_info.column_names)
coef

Intercept    0.312910
x0          -0.079106
x1          -0.265464
dtype: float64

In [30]:
#Patsy 용법을 데이터 변환하기
y, X = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) +1)', data)
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

In [31]:
y, X = patsy.dmatrices('y ~ standardize(x0) + center(x1)', data)

In [32]:
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

In [33]:
new_data = pd.DataFrame({'x0' : [6, 7, 8, 9],
                        'x1' : [3.1, -0.5, 0, 2.3],
                        'y' : [1, 2, 3, 4]})

In [34]:
new_X = patsy.build_design_matrices([X.design_info], new_data)
new_X

[DesignMatrix with shape (4, 3)
   Intercept  standardize(x0)  center(x1)
           1          2.12132        3.87
           1          2.82843        0.27
           1          3.53553        0.77
           1          4.24264        3.07
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

In [35]:
y, X = patsy.dmatrices('y ~ I(x0 +x1)', data)
X

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1        1.01
          1        1.99
          1        3.25
          1       -0.10
          1        5.00
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

In [37]:
#범주형 데이터와 Patsy
data = pd.DataFrame({
    'key1' : ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'],
    'key2' : [0, 1, 0, 1, 0, 1, 0, 0],
    'v1' : [1, 2, 3, 4, 5, 6, 7, 8],
    'v2' : [-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]
})

In [38]:
y, X = patsy.dmatrices('v2 ~ key1', data)
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [39]:
#13.3 statsmodels 소개
#statsmodels이 포함하는 모델
#선형 모델, 일반 선형 모델, 로버스트 선형 모델
#선형 복합효과(Linear Mixed Effects, LME) 모델 
#ANOVA 메서드
#시계열 처리 및 상태 공간 모델
#일반적률추정법(Generalized Method of Moments, GMM)

In [40]:
pip install statsmodels


You should consider upgrading via the 'C:\Users\seven\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [41]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [42]:
def dnorm(mean, variance, size = 1): 
    if isinstance(size, int):
        size = size,
    return mean + np.sqrt(variance)*np.random.randn(*size)

np.random.seed(12345)

N = 100
X = np.c_[dnorm(0, 0.4, size = N),
        dnorm(0, 0.6, size = N),
        dnorm(0, 0.2, size = N)]
eps = dnorm(0, 0.1, size =N)
beta = [0.1, 0.3, 0.5]

y = np.dot(X, beta) + eps

In [46]:
help(dnorm) #dnorm : 정규분포 데이터 생성

Help on function dnorm in module __main__:

dnorm(mean, variance, size=1)



In [47]:
X[:5]

array([[-0.12946849, -1.21275292,  0.50422488],
       [ 0.30291036, -0.43574176, -0.25417986],
       [-0.32852189, -0.02530153,  0.13835097],
       [-0.35147471, -0.71960511, -0.25821463],
       [ 1.2432688 , -0.37379916, -0.52262905]])

In [48]:
y[:5]

array([ 0.42786349, -0.67348041, -0.09087764, -0.48949442, -0.12894109])

In [50]:
X_model = sm.add_constant(X) #선형 모델의 intercept을 기존 행렬에 더하기
X_model[:5]

array([[ 1.        , -0.12946849, -1.21275292,  0.50422488],
       [ 1.        ,  0.30291036, -0.43574176, -0.25417986],
       [ 1.        , -0.32852189, -0.02530153,  0.13835097],
       [ 1.        , -0.35147471, -0.71960511, -0.25821463],
       [ 1.        ,  1.2432688 , -0.37379916, -0.52262905]])

In [52]:
model = sm.OLS(y, X) # OLS : 최소제곱 / sm.OLS : 최소제곱 선형회귀
results = model.fit() #model.fit : 회귀 결과 객체를 반환
results.params

array([0.17826108, 0.22303962, 0.50095093])

In [54]:
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.430
Model:                            OLS   Adj. R-squared (uncentered):              0.413
Method:                 Least Squares   F-statistic:                              24.42
Date:                Tue, 22 Jun 2021   Prob (F-statistic):                    7.44e-12
Time:                        11:07:14   Log-Likelihood:                         -34.305
No. Observations:                 100   AIC:                                      74.61
Df Residuals:                      97   BIC:                                      82.42
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [55]:
data = pd.DataFrame(X, columns=['col0', 'col1', 'col2'])
data['y'] = y
data[:5]

,col0,col1,col2,y
0,-0.129468,-1.212753,0.504225,0.427863
1,0.302910,-0.435742,-0.254180,-0.673480
2,-0.328522,-0.025302,0.138351,-0.090878
3,-0.351475,-0.719605,-0.258215,-0.489494
4,1.243269,-0.373799,-0.522629,-0.128941


In [56]:
results = smf.ols('y ~ col0 + col1 + col2', data = data).fit()
results.params

Intercept    0.033559
col0         0.176149
col1         0.224826
col2         0.514808
dtype: float64

In [57]:
results.tvalues

Intercept    0.952188
col0         3.319754
col1         4.850730
col2         6.303971
dtype: float64

In [58]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.435
Model:                            OLS   Adj. R-squared:                  0.418
Method:                 Least Squares   F-statistic:                     24.68
Date:                Tue, 22 Jun 2021   Prob (F-statistic):           6.37e-12
Time:                        11:11:21   Log-Likelihood:                -33.835
No. Observations:                 100   AIC:                             75.67
Df Residuals:                      96   BIC:                             86.09
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0336      0.035      0.952      0.3

In [59]:
results.predict(data[:5])

0   -0.002327
1   -0.141904
2    0.041226
3   -0.323070
4   -0.100535
dtype: float64

In [60]:
#13.3.2 시계열 처리 예측
init_x = 4

import random
values = [init_x, init_x]
N = 1000

b0 = 0.8
b1 = -0.4
noise = dnorm(0, 0.1, N)
for i in range(N):
    new_x = values[-1]*b0 + values[-2] *b1 + noise[i]
    values.append(new_x)

In [62]:
MAXLAGS = 5
model = sm.tsa.AR(values)
results = model.fit(MAXLAGS)

In [63]:
results.params

array([-0.00616093,  0.78446347, -0.40847891, -0.01364148,  0.01496872,
        0.01429462])

In [1]:
import pandas as pd
import numpy as np

In [5]:
train = pd.read_csv('C:/Users/seven/OneDrive/바탕 화면/Python Workspace/Python-master/Python for Data analysis/datasets/titanic/train.csv')
test = pd.read_csv('C:/Users/seven/OneDrive/바탕 화면/Python Workspace/Python-master/Python for Data analysis/datasets/titanic/test.csv')

In [6]:
train[:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S


In [7]:
#statsmodels or scikit-learn은 일반적으로 누락된 데이터를 처리하지 못함
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [9]:
#특정 승객이 생존할 것인지 예측하는 것이 과제
#학습 데이터셋에 모델을 피팅하고 나서 테스트 데이터셋으로 검증
#결측치를 보완하기 위한 여러가지 방법 중 학습데이터 셋의 중간값으로 채워 넣자
impute_value = train['Age'].median()
train['Age'] = train['Age'].fillna(impute_value)
test['Age'] = test['Age'].fillna(impute_value)

In [10]:
#IsFemale 컬럼을 추가해서 'Sex'컬럼을 인코딩
train['IsFemale'] = (train['Sex'] == 'female').astype(int)
test['IsFemale'] = (test['Sex'] == 'female').astype(int)
predictors = ['Pclass', 'IsFemale', 'Age']
X_train = train[predictors].values
X_test = test[predictors].values
y_train = train['Survived'].values
X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [12]:
pip install sklearn

Using legacy 'setup.py install' for sklearn, since package 'wheel' is not installed.
    Running setup.py install for sklearn: started
    Running setup.py install for sklearn: finished with status 'done'
Note: you may need to restart the kernel to use updated packages.
You should consider upgrading via the 'C:\Users\seven\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [13]:
#scikit-learn의 logisticRegression 모델을 이용해서 model 인스턴스를 생성
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [14]:
#model의 fit 메서드를 이용해서 이 모델을 학습 데이터에 피팅
model.fit(X_train, y_train)

LogisticRegression()

In [15]:
y_predictor = model.predict(X_test) #model.predict : 테스트 데이터셋으로 예측
y_predictor[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [16]:
#학습 데이터에 오버피팅되는 것을 피할 수 있도록 교차검증 같은 기법을 활용 => 새로운 데이터에 대해 좀 더 견고하거나 예측 성능을 높여줌
from sklearn.linear_model import LogisticRegressionCV
model_cv = LogisticRegressionCV(10)
model_cv.fit(X_train, y_train)

C:\Users\seven\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass Cs=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


LogisticRegressionCV()

In [18]:
#cross_val_score : 데이터를 분할하는 과정을 도와줌
#Ex) 학습 데이터를 겹치지 않는 4개의 그룹으로 나누기
from sklearn.model_selection import cross_val_score
model = LogisticRegression(C = 10)
scores = cross_val_score(model, X_train, y_train, cv = 4)
scores

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])