In [2]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [3]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [6]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [6]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                    [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna() #dropna 있는 row 모두 제거
data

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [8]:
cleaned 

,0,1,2
0,1.0,6.5,3.0


In [8]:
data.dropna(how = 'all') #모든 row에 NA값이 있을때만

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
3,NaN,6.5,3.0


In [11]:
data[4] = NA #data[4] : 4번째 컬럼
data

,0,1,2,4
0,1.0,6.5,3.0,NaN
1,1.0,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,6.5,3.0,NaN


In [12]:
data.dropna(axis= 1, how= 'all') #axis = 1 : 컬럼을 기준으로

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [10]:
data.dropna(axis = 0, how = 'all') #axis = 0 : row를 기준으로

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
3,NaN,6.5,3.0


In [11]:
df = pd.DataFrame(np.random.randn(7, 3))
df

,0,1,2
0,1.062020,-1.510191,1.672222
1,0.123060,2.098531,0.932243
2,0.650586,1.985612,-0.677336
3,0.293084,0.514623,2.308911
4,1.368669,0.024540,1.493027
5,-0.179816,1.589776,-0.499668
6,-0.071601,0.280197,-0.752671


In [14]:
df.iloc[:4, 1] = NA #iloc : 숫자로 위치 찾기
df.iloc[:2, 2] = NA
df

,0,1,2
0,-0.983181,NaN,NaN
1,0.250597,NaN,NaN
2,0.615463,NaN,-0.731676
3,-0.043794,NaN,1.171153
4,-0.760065,1.019660,0.271570
5,0.634115,0.191274,0.079400
6,-1.083178,-0.416948,-0.461002


In [15]:
df.dropna() # NA가 있는 row를 모두 drop

,0,1,2
4,-0.760065,1.019660,0.271570
5,0.634115,0.191274,0.079400
6,-1.083178,-0.416948,-0.461002


In [16]:
df.dropna(thresh = 2) # thresh = n : 축을 기준으로 NA값이 n개 미만이면 삭제

,0,1,2
2,0.615463,NaN,-0.731676
3,-0.043794,NaN,1.171153
4,-0.760065,1.019660,0.271570
5,0.634115,0.191274,0.079400
6,-1.083178,-0.416948,-0.461002


In [17]:
df.dropna(thresh = 1) 

,0,1,2
0,-0.983181,NaN,NaN
1,0.250597,NaN,NaN
2,0.615463,NaN,-0.731676
3,-0.043794,NaN,1.171153
4,-0.760065,1.019660,0.271570
5,0.634115,0.191274,0.079400
6,-1.083178,-0.416948,-0.461002


In [18]:
df.fillna(0)

,0,1,2
0,-0.983181,0.000000,0.000000
1,0.250597,0.000000,0.000000
2,0.615463,0.000000,-0.731676
3,-0.043794,0.000000,1.171153
4,-0.760065,1.019660,0.271570
5,0.634115,0.191274,0.079400
6,-1.083178,-0.416948,-0.461002


In [20]:
df.fillna({1: 0.5, 2: 0}) # 컬럼 1의 NA -> 0.5 / 컬럼 2의 NA -> 0

,0,1,2
0,-0.983181,0.500000,0.000000
1,0.250597,0.500000,0.000000
2,0.615463,0.500000,-0.731676
3,-0.043794,0.500000,1.171153
4,-0.760065,1.019660,0.271570
5,0.634115,0.191274,0.079400
6,-1.083178,-0.416948,-0.461002


In [21]:
_ = df.fillna(0, inplace = True)
df

,0,1,2
0,-0.983181,0.000000,0.000000
1,0.250597,0.000000,0.000000
2,0.615463,0.000000,-0.731676
3,-0.043794,0.000000,1.171153
4,-0.760065,1.019660,0.271570
5,0.634115,0.191274,0.079400
6,-1.083178,-0.416948,-0.461002


In [22]:
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

,0,1,2
0,0.426074,0.470625,0.028569
1,-0.103848,-1.195678,1.635880
2,0.076828,NaN,-0.178189
3,-0.841304,NaN,1.277020
4,0.158873,NaN,NaN
5,1.835482,NaN,NaN


In [23]:
df.fillna(method = 'ffill') #method = 'ffill' : NA의 바로 위의 값으로 채워짐

,0,1,2
0,0.426074,0.470625,0.028569
1,-0.103848,-1.195678,1.635880
2,0.076828,-1.195678,-0.178189
3,-0.841304,-1.195678,1.277020
4,0.158873,-1.195678,1.277020
5,1.835482,-1.195678,1.277020


In [29]:
df.fillna(method= 'ffill', limit= 2) #limit : 채워지는 NA의 수를 제한

,0,1,2
0,0.426074,0.470625,0.028569
1,-0.103848,-1.195678,1.635880
2,0.076828,-1.195678,-0.178189
3,-0.841304,-1.195678,1.277020
4,0.158873,NaN,1.277020
5,1.835482,NaN,1.277020


In [30]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [31]:
data = pd.DataFrame({'k1':['one', 'two']*3 + ['two'],
                    'k2' : [1, 1, 2, 3, 3, 4, 4]})
data

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4
6,two,4


In [33]:
data.duplicated() #duplicated : 중복체크

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [34]:
data.drop_duplicates() #drop_duplicates : 중복 제거

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4


In [35]:
data['v1'] = range(7)
data

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
5,two,4,5
6,two,4,6


In [37]:
data.drop_duplicates(['k1'])

,k1,k2,v1
0,one,1,0
1,two,1,1


In [38]:
data.duplicated(['k1'])

0    False
1    False
2     True
3     True
4     True
5     True
6     True
dtype: bool

In [39]:
data.drop_duplicates(['k1', 'k2'], keep = 'last')

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
6,two,4,6


In [40]:
data = pd.DataFrame({'food' : ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'], 'ounces' : [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

,food,ounces
0,bacon,4.0
1,pulled pork,3.0
2,bacon,12.0
3,Pastrami,6.0
4,corned beef,7.5
5,Bacon,8.0
6,pastrami,3.0
7,honey ham,5.0
8,nova lox,6.0


In [42]:
meat_to_animal = {
    'bacon' : 'pig', 
    'pulled pork' : 'pig',
    'pastrami' : 'cow',
    'corned beef' : 'cow',
    'honey ham' : 'pig',
    'nova lox' : 'salmon'
}

In [43]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [44]:
data['animal'] = lowercased.map(meat_to_animal) 
data

,food,ounces,animal
0,bacon,4.0,pig
1,pulled pork,3.0,pig
2,bacon,12.0,pig
3,Pastrami,6.0,cow
4,corned beef,7.5,cow
5,Bacon,8.0,pig
6,pastrami,3.0,cow
7,honey ham,5.0,pig
8,nova lox,6.0,salmon


In [45]:
data['food'].map(lambda x : meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [46]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [47]:
data.replace(-999, np.nan) #replace : 값 대체하기

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [48]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [49]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [50]:
data.replace({-999 : np.nan, -1000 : 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [52]:
data = pd.DataFrame(np.arange(12).reshape((3,4)), #파이썬은 아무런 지정이 없으면 row부터 채워짐
                    index = ['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
New York,8,9,10,11


In [53]:
transform = lambda x : x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [54]:
data.index = data.index.map(transform)
data

,one,two,three,four
OHIO,0,1,2,3
COLO,4,5,6,7
NEW,8,9,10,11


In [55]:
data.rename(index = str.title, columns=str.upper)

,ONE,TWO,THREE,FOUR
Ohio,0,1,2,3
Colo,4,5,6,7
New,8,9,10,11


In [56]:
data.rename(index={'OHIO' : 'INDIANA'},
            columns = {'three' : 'peekaboo'})

,one,two,peekaboo,four
INDIANA,0,1,2,3
COLO,4,5,6,7
NEW,8,9,10,11


In [57]:
data.rename(index= {'OHIO' : 'INDIANA'}, inplace=True)
data

,one,two,three,four
INDIANA,0,1,2,3
COLO,4,5,6,7
NEW,8,9,10,11


In [59]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [60]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [63]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [61]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False) # right = False : 범위의 왼쪽 포함

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [62]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names) #labels : 범위 이름 붙이기

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [68]:
data = np.random.randn(20)
pd.cut(data, 4, precision= 2) # precision : 소수점 자릿수

[(0.74, 1.43], (-0.64, 0.046], (0.046, 0.74], (-0.64, 0.046], (-0.64, 0.046], ..., (-0.64, 0.046], (-0.64, 0.046], (0.046, 0.74], (0.046, 0.74], (0.74, 1.43]]
Length: 20
Categories (4, interval[float64]): [(-1.34, -0.64] < (-0.64, 0.046] < (0.046, 0.74] < (0.74, 1.43]]

In [71]:
data = np.random.randn(1000)
cats = pd.qcut(data, 4) #qcut : 표본 변위수를 기반으로 데이터를 분할
cats

[(-0.708, -0.00229], (-2.86, -0.708], (-0.00229, 0.666], (-0.00229, 0.666], (-0.00229, 0.666], ..., (0.666, 3.032], (-0.00229, 0.666], (0.666, 3.032], (-0.708, -0.00229], (-0.708, -0.00229]]
Length: 1000
Categories (4, interval[float64]): [(-2.86, -0.708] < (-0.708, -0.00229] < (-0.00229, 0.666] < (0.666, 3.032]]

In [72]:
pd.value_counts(cats)

(0.666, 3.032]        250
(-0.00229, 0.666]     250
(-0.708, -0.00229]    250
(-2.86, -0.708]       250
dtype: int64

In [73]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.324, -0.00229], (-1.324, -0.00229], (-0.00229, 1.224], (-0.00229, 1.224], (-0.00229, 1.224], ..., (-0.00229, 1.224], (-0.00229, 1.224], (-0.00229, 1.224], (-1.324, -0.00229], (-1.324, -0.00229]]
Length: 1000
Categories (4, interval[float64]): [(-2.86, -1.324] < (-1.324, -0.00229] < (-0.00229, 1.224] < (1.224, 3.032]]

In [74]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,-0.013535,0.008745,-0.010644,0.035066
std,0.995143,0.991152,1.029363,0.963874
min,-3.311753,-3.118587,-3.979539,-2.973954
25%,-0.685412,-0.679211,-0.688175,-0.646806
50%,-0.002191,0.063979,0.022578,0.003900
75%,0.622050,0.645079,0.648929,0.669654
max,3.042093,2.983948,2.841042,3.141569


In [78]:
col = data[2]
col[np.abs(col) > 3]

88    -3.979539
181   -3.039294
Name: 2, dtype: float64

In [76]:
data[(np.abs(data) > 3).any(1)] #any(1) : 절대값이 3을 초과하는 모든 row를 선택

,0,1,2,3
20,-3.470143,-0.052977,0.131505,1.747781
223,-0.047576,0.061879,-0.081788,-3.334349
255,-3.407925,1.727517,0.430786,0.492751
382,0.442380,-1.252780,3.203825,0.498781
428,3.018864,-0.869507,1.003627,1.818474
608,-3.222409,0.682617,-0.520404,1.336493
761,0.264846,1.815948,2.135324,-3.567526
983,-1.392884,-3.237020,0.036582,-1.355687


In [79]:
data[np.abs(data) > 3] = np.sign(data) * 3 #np.sign(data) : data값이 양수 or 음수 -> 1 or -1
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,-0.013296,0.008892,-0.009625,0.034924
std,0.993936,0.990696,1.025928,0.963427
min,-3.000000,-3.000000,-3.000000,-2.973954
25%,-0.685412,-0.679211,-0.688175,-0.646806
50%,-0.002191,0.063979,0.022578,0.003900
75%,0.622050,0.645079,0.648929,0.669654
max,3.000000,2.983948,2.841042,3.000000


In [80]:
np.sign(data).head()

,0,1,2,3
0,1.0,1.0,1.0,1.0
1,1.0,-1.0,-1.0,1.0
2,1.0,1.0,-1.0,1.0
3,1.0,-1.0,1.0,-1.0
4,1.0,1.0,-1.0,-1.0


In [2]:
df = pd.DataFrame(np.arange( 5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5) #row를 임의 순서로 재배치
sampler

array([2, 1, 0, 3, 4])

In [3]:
df

,0,1,2,3
0,0,1,2,3
1,4,5,6,7
2,8,9,10,11
3,12,13,14,15
4,16,17,18,19


In [4]:
df.take(sampler) #take : row 인덱스 가져오기

,0,1,2,3
1,4,5,6,7
4,16,17,18,19
3,12,13,14,15
0,0,1,2,3
2,8,9,10,11


In [4]:
df.sample(n = 2) #sample : 치환없이 일부만 임의로 선택

,0,1,2,3
0,0,1,2,3
1,4,5,6,7


In [5]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n = 10, replace = True) #replace : 반복허용
draws

0    5
0    5
1    7
1    7
4    4
4    4
1    7
4    4
0    5
1    7
dtype: int64

In [6]:
df = pd.DataFrame({'key' : ['b', 'b', 'a', 'c', 'a', 'b'],
                    'data1' : range(6)})

pd.get_dummies(df['key'])

,a,b,c
0,0,1,0
1,0,1,0
2,1,0,0
3,0,0,1
4,1,0,0
5,0,1,0


In [7]:
df

,key,data1
0,b,0
1,b,1
2,a,2
3,c,3
4,a,4
5,b,5


In [8]:
dummies = pd.get_dummies(df['key'], prefix='key') #prefix : 접두어를 추가
df_with_dummy = df[['data1']].join(dummies) #join : DF병합
df_with_dummy

,data1,key_a,key_b,key_c
0,0,0,1,0
1,1,0,1,0
2,2,1,0,0
3,3,0,0,1
4,4,1,0,0
5,5,0,1,0


In [9]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('C:/Users/seven/OneDrive/바탕 화면/Python Workspace/Python-master/Python for Data analysis/datasets/movielens/movies.dat', sep = '::', header= None, names= mnames)
movies[:10]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py:765: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return read_csv(**locals())


,movie_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller


In [10]:
all_genres = []
for x in movies.genres: 
    all_genres.extend(x.split('|'))

genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [11]:
zero_matrix = np.zeros((len(movies), len(genres))) #0으로 된 matrix 생성/row의 수 : len(movies), column의 수 : len(genres)
dummies = pd.DataFrame(zero_matrix, columns=genres)
dummies

,Animation,Children's,Comedy,Adventure,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Sci-Fi,Documentary,War,Musical,Mystery,Film-Noir,Western
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3879,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3880,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3881,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [12]:
zero_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
len(movies)

3883

In [16]:
len(genres)

18

In [17]:
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [18]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [19]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [20]:
dummies

,Animation,Children's,Comedy,Adventure,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Sci-Fi,Documentary,War,Musical,Mystery,Film-Noir,Western
0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3879,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3880,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3881,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [21]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic

,movie_id,title,genres,Genre_Animation,Genre_Children's,Genre_Comedy,Genre_Adventure,Genre_Fantasy,Genre_Romance,Genre_Drama,...,Genre_Crime,Genre_Thriller,Genre_Horror,Genre_Sci-Fi,Genre_Documentary,Genre_War,Genre_Musical,Genre_Mystery,Genre_Film-Noir,Genre_Western
0,1,Toy Story (1995),Animation|Children's|Comedy,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Jumanji (1995),Adventure|Children's|Fantasy,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Grumpier Old Men (1995),Comedy|Romance,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Waiting to Exhale (1995),Comedy|Drama,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Father of the Bride Part II (1995),Comedy,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,3948,Meet the Parents (2000),Comedy,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3879,3949,Requiem for a Dream (2000),Drama,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3880,3950,Tigerland (2000),Drama,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3881,3951,Two Family House (2000),Drama,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [22]:
np.random.seed(12345)
values = np.random.randn(10)
values

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474])

In [24]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

,"(0.0, 0.2]","(0.2, 0.4]","(0.4, 0.6]","(0.6, 0.8]","(0.8, 1.0]"
0,0,0,0,0,0
1,0,0,1,0,0
2,0,0,0,0,0
3,0,0,0,0,0
4,0,0,0,0,0
5,0,0,0,0,0
6,1,0,0,0,0
7,0,1,0,0,0
8,0,0,0,1,0
9,0,0,0,0,0


In [25]:
pd.cut(values, bins)

[NaN, (0.4, 0.6], NaN, NaN, NaN, NaN, (0.0, 0.2], (0.2, 0.4], (0.6, 0.8], NaN]
Categories (5, interval[float64]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] < (0.8, 1.0]]

In [26]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [27]:
pieces = [x.strip() for x in val.split(',')] #strip : 공백문자(줄바꿈 문자 포함) 제거
pieces

['a', 'b', 'guido']

In [28]:
first, second, third = pieces
first +'::' + second + '::' + third

'a::b::guido'

In [29]:
'::'.join(pieces)

'a::b::guido'

In [30]:
'guido' in val

True

In [44]:
val.index(',') #index : 부분문자열의 위치 찾기

1

In [45]:
val.find(':') #find : 부분문자열의 위치 찾기 -> 찾지 못하면 -1 출력

-1

In [46]:
val.index(':') #찾지 못하면 예외 발생

ValueError: substring not found

In [31]:
val.count(',')

2

In [33]:
val.replace(',', '::') #replace : 문자열 대체

'a::b:: guido'

In [34]:
val.replace(',', '')

'ab guido'

In [35]:
import re
text = 'foo bar\t baz \tqux'
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [36]:
text

'foo bar\t baz \tqux'

In [37]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [38]:
regex

re.compile(r'\s+', re.UNICODE)

In [39]:
regex.findall(text)

[' ', '\t ', ' \t']

In [67]:
text = '''Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@gmail.com
'''

pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

regex = re.compile(pattern, flags=re.IGNORECASE)

In [54]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@gmail.com']

In [56]:
m = regex.search(text)
m
text[m.start():m.end()]

'dave@google.com'

In [58]:
print(regex.match(text))

None


In [59]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [75]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags= re.IGNORECASE)

In [77]:
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [78]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'gmail', 'com')]

In [82]:
data = {'Dave' : 'dave@google.com', 'Steve' : 'steve@gmail.com','Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [83]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [84]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [85]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [86]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [88]:
matches = data.str.match(pattern, flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object